### ISSUE TITLE
ULTRABC breaks WASD map movement, tab completion

### ISSUE THREAD

**Issue by u3shit** [tetris245/ULTRAbc#4]
`KeyDown` functions return a boolean indicating whether the event was handled. `ULTRAChatRoomKeyDown` always returns `null`, breaking things, like tab completion or WASD map movement in R102.

I'm attaching a patch that fixes the problem for me (I can't create a PR, github doesn't allow me to push anymore).
[0001-Fix-KeyDown-handler-return-value.patch.txt](https://github.com/tetris245/ULTRAbc/files/14635050/0001-Fix-KeyDown-handler-return-value.patch.txt)

**Comment by tetris245** [comment]
Thank you for your report and the patch. I will make a hotfix after some testing.

Hava a nice day :)

**Comment by tetris245** [comment]
Hotfix done .... thanks again for your work!
