### ISSUE TITLE
Pain moans ignore arousal level

### ISSUE THREAD

**Issue by Nikky90506** [tetris245/ULTRAbc#6]
Hello!
It looks like currently (actually it's like this for quite some time) pain moans ignore arousal level.

I tried debugging and it seems here
```
 function M_MOANER_miscReactions(data) {
        var Factor = Math.floor(Player.ArousalSettings.Progress / 20);
        //get the moan type to apply
        //data to generate the moans
        if (reaction == 1) {
            var moan = getPainMoan(Factor, Math.random() * 300);
        }
```
expectation is, that `getPainMoan(Factor, seed)` will be called, but it's actually `getPainMoan()`.

Turns out (surprising to me) JavaScript doesn't support function overloading and that's probably why it didn't work as I assume is expected.

The most simple way to fix this would be giving these two functions different names.
Same problem probably exists with `getTickleMoan()` and `getTickleMoan(Factor, seed)`. I'm not sure if there are other cases.

**Comment by tetris245** [comment]
Thanks for reporting the issue ... I will take a look and make some tests

**Comment by tetris245** [comment]
Well, renaming one of the functions will not make the Moaner work as you think, because actually the arousal level is not linked to specific moans for the spank or the tickle activity, but to specific moans to the change of vibe level (and activities considered as similar). It was designed like that since the beginning in the original stand-alone Moaner for the Spank activity and I've followed the same approach when adding the Tickle activity.

If you look at the Moaner profiles, you will see that the arousal levels are independant from the spank and tickle activities.

**Comment by tetris245** [comment]
But apparently, the function was getSpankMoan(Factor, seed) { in the original Moaner. So I guess the confusion comes from a change I've made later.

**Comment by tetris245** [comment]
Anyway, I will leave it as it is. Changing names of one of the functions has as effect nothing or that no any moan is produced, according the function whose name is changed.

**Comment by tetris245** [comment]
I'm still doing tests ... Maybe I will find the trick!

**Comment by Nikky90506** [comment]
Thanks for looking into it. 
The thing is, I remember it working differently before in UBC/QAM. Originally when my character was spanked it were pleasure moans. I assumed it was because of activity preference settings, so GetActivityTaste seems like a good lead.
The part about changing function names was just a guess to be honest as I didn't 
want to make a working fork just to test a simple change. And also didn't manage to make local script override work.

**Comment by tetris245** [comment]
It's probably wrong since Ben has compressed Player.ArousalSettings.Activity

So the conditions to distinct pain and pleasure need to be written differently!

**Comment by tetris245** [comment]
Finally found how to fix that. Your first guess was useful too, I need indeed to change the name of the 'simplified' function, but it was not enough: I had to read differently the content of Player.ArousalSettings.Activity.

I will make later a hotfix.

**Comment by tetris245** [comment]
Hotfix done :)

Thanks again for your report!
